on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: ./
        with:
          dist-dir: public
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
